package com.droidsiege.ui.theme

import androidx.compose.ui.graphics.Color

val NavyPrimaryLight = Color(0xFF1C4E80)
val NavyOnPrimaryLight = Color(0xFFFFFFFF)
val NavyPrimaryContainerLight = Color(0xFFD3E4FF)
val NavyOnPrimaryContainerLight = Color(0xFF001C38)
val NavySecondaryLight = Color(0xFF535F70)
val NavyOnSecondaryLight = Color(0xFFFFFFFF)
val NavySecondaryContainerLight = Color(0xFFD7E3F8)
val NavyOnSecondaryContainerLight = Color(0xFF101C2B)
val NavyTertiaryLight = Color(0xFF6B5677)
val NavyOnTertiaryLight = Color(0xFFFFFFFF)
val NavyTertiaryContainerLight = Color(0xFFF3DAFF)
val NavyOnTertiaryContainerLight = Color(0xFF251431)
val NavyErrorLight = Color(0xFFBA1A1A)
val NavyOnErrorLight = Color(0xFFFFFFFF)
val NavyErrorContainerLight = Color(0xFFFFDAD6)
val NavyOnErrorContainerLight = Color(0xFF410002)
val NavyBackgroundLight = Color(0xFFF8F9FB)
val NavyOnBackgroundLight = Color(0xFF191C20)
val NavySurfaceLight = Color(0xFFF8F9FB)
val NavyOnSurfaceLight = Color(0xFF191C20)
val NavySurfaceVariantLight = Color(0xFFDFE2EB)
val NavyOnSurfaceVariantLight = Color(0xFF43474E)
val NavyOutlineLight = Color(0xFF73777F)

val NavyPrimaryDark = Color(0xFFA2C9FF)
val NavyOnPrimaryDark = Color(0xFF00325B)
val NavyPrimaryContainerDark = Color(0xFF1A4167)
val NavyOnPrimaryContainerDark = Color(0xFFD3E4FF)
val NavySecondaryDark = Color(0xFFBBC7DB)
val NavyOnSecondaryDark = Color(0xFF253140)
val NavySecondaryContainerDark = Color(0xFF3B4858)
val NavyOnSecondaryContainerDark = Color(0xFFD7E3F8)
val NavyTertiaryDark = Color(0xFFD8B9E7)
val NavyOnTertiaryDark = Color(0xFF3B2946)
val NavyTertiaryContainerDark = Color(0xFF533F5E)
val NavyOnTertiaryContainerDark = Color(0xFFF3DAFF)
val NavyErrorDark = Color(0xFFFFB4AB)
val NavyOnErrorDark = Color(0xFF690005)
val NavyErrorContainerDark = Color(0xFF93000A)
val NavyOnErrorContainerDark = Color(0xFFFFDAD6)
val NavyBackgroundDark = Color(0xFF111418)
val NavyOnBackgroundDark = Color(0xFFE1E2E6)
val NavySurfaceDark = Color(0xFF111418)
val NavyOnSurfaceDark = Color(0xFFE1E2E6)
val NavySurfaceVariantDark = Color(0xFF43474E)
val NavyOnSurfaceVariantDark = Color(0xFFC3C7CF)
val NavyOutlineDark = Color(0xFF8D9199)
