build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

complexity:
  LongMethod:
    threshold: 120
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 120
  ReturnCount:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview'

exceptions:
  TooGenericExceptionCaught:
    active: false
